### ISSUE TITLE
Why does the universal function take 'React' as argument

### ISSUE THREAD

**Issue by Maximilianos** [ericelliott/react-easy-universal#1]
Minor question really, just wondering at the specific reasons. Why not `import React from 'react';` in the `react-easy-universal` module? Is it just a pattern you prefer, if so why?

**Comment by mastilver** [comment]
From: https://medium.com/javascript-scene/baby-s-first-reaction-2103348eccdd#.l32sujhrb
> We’re exporting a factory instead of the component itself. In this example, it lets the caller pass in the `React` instance, which can avoid common problems with multiple instances of React on the same page. That can cause confusing errors. But it also allows you to add configuration options to your component later on, should you need to.

Although I don't think it's a real issue with the latest `npm` and `react`

**Comment by ericelliott** [comment]
I'm not sure if it's a source of bugs anymore, but it also gives you the freedom to load React from CDN in the client app, which may save on client payloads.

**Comment by Maximilianos** [comment]
Thanks, ok the CDN use case makes sense. Although with webpack one could definitely use the [externals feature](https://webpack.github.io/docs/library-and-externals.html#applications-and-externals) for that. However I do see how your implementation makes this simpler in that one does not need to even bother with that.

I would have gone with the webpack way because it feels cleaner to me for some reason, but that is absolutely just my personal pref. 

Looking forward to the rest of the code. :+1:

**Comment by ericelliott** [comment]
> Although with webpack one could definitely use the externals feature for that.

Yep, I'm aware of that, but we won't have control of the end user's webpack config, and the whole point of this lib is to give users an app that *just works* out of the box without any fancy config requirements. And IMO, passing in `React` is a tiny price to pay for that.
