### ISSUE TITLE
Necessary?

### ISSUE THREAD

**Issue by kennetpostigo** [ericelliott/react-easy-universal#3]
Hey,

I've been working on my own universal react+redux+immutable project and I ran to a few roadblocks on my way to getting it running seamlessly.

Most of my the roadblocks arose because It was my first time setting up a "universal" react project and also because it was my first time setting up split points through webpack code-splitting.

I based a lot of the majority of my project based on this [rackt example](https://github.com/rackt/example-react-router-server-rendering-lazy-routes) for getting react-router setup with code-splitting and [this](https://github.com/gaearon/react-transform-boilerplate) boilerplate made by Dan Abramov for getting a tight feedback loop.

I ask if this is necessary because to set this up really didn't change my existing codebase. I had to add the following:
1. Server implementation
2. Route Configuration with `match`
3. Update the client-side store to get hydrated from the server.

Rackt provides great examples with explanations to get started. So maybe this would be better as a spec or guideline?

**Comment by ericelliott** [comment]
Nope. Having set this up in several projects, I can assure you that a ton of time will be saved -- at least for me. We're doing this.
