### ISSUE TITLE
Is your package just reexport of redux, react, react-router, react-redux-router

### ISSUE THREAD

**Issue by stepancar** [ericelliott/react-easy-universal#6]

**Comment by stepancar** [comment]
How you will support your lib? All this libs changing faster than light speed :)

**Comment by ericelliott** [comment]
No, it is not just a re-export. It provides a high-level API that automatically hooks up the reducers to the store, the routes to the express route handlers, the history API, debuggers in dev, etc...

Basically it handles all the boilerplate complexity of wrangling all these different tools so you can focus on what matters to your app: your app's routes, your apps reducers, etc...

**Comment by ericelliott** [comment]
Note: It's not finished. I'm hooking up the server-render as we speak. You can track progress in [this pull request](https://github.com/ericelliott/react-easy-universal/pull/5/files).
